// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIwyMHl8YCelfnKud_DDV1Au83qQIHXvg',
    appId: '1:893825066478:web:5dba21bbe6a8e9fd4d9aff',
    messagingSenderId: '893825066478',
    projectId: 'byteverse-4f2b5',
    authDomain: 'byteverse-4f2b5.firebaseapp.com',
    storageBucket: 'byteverse-4f2b5.appspot.com',
    measurementId: 'G-V67XLXRJSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANBuLve2Wnpqum8JNgWhYsc0je3FKqZ7o',
    appId: '1:893825066478:android:294b9668522bb43a4d9aff',
    messagingSenderId: '893825066478',
    projectId: 'byteverse-4f2b5',
    storageBucket: 'byteverse-4f2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6AGeQNE2npoCKGbeSXpoLp65PCI7Qph4',
    appId: '1:893825066478:ios:f3dbd90bd1c663934d9aff',
    messagingSenderId: '893825066478',
    projectId: 'byteverse-4f2b5',
    storageBucket: 'byteverse-4f2b5.appspot.com',
    iosBundleId: 'com.example.huma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6AGeQNE2npoCKGbeSXpoLp65PCI7Qph4',
    appId: '1:893825066478:ios:f3dbd90bd1c663934d9aff',
    messagingSenderId: '893825066478',
    projectId: 'byteverse-4f2b5',
    storageBucket: 'byteverse-4f2b5.appspot.com',
    iosBundleId: 'com.example.huma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIwyMHl8YCelfnKud_DDV1Au83qQIHXvg',
    appId: '1:893825066478:web:e6b836b7c27fd9834d9aff',
    messagingSenderId: '893825066478',
    projectId: 'byteverse-4f2b5',
    authDomain: 'byteverse-4f2b5.firebaseapp.com',
    storageBucket: 'byteverse-4f2b5.appspot.com',
    measurementId: 'G-B6QGPKK8GN',
  );
}
